//! The builder skill's generated references (RFC-0017 §S1). The one rule that keeps a skill from
//! lying about nuthatch is: **generate what can be generated.** `cli-reference.md` is rendered from
//! clap's own metadata here - the binary describing itself is the most drift-proof source we have -
//! and a CI test (`tests/skill_refs.rs`) regenerates it and fails the build on any drift, plus fails
//! if an authored skill file mentions a `--flag` this reference doesn't contain.
//!
//! Nothing here runs in the data path; it's a dev/authoring tool exposed as a hidden subcommand so
//! the reference is always in sync with the binary that ships.

use std::path::Path;

use anyhow::{Context, Result};
use clap::CommandFactory;

use crate::cli::Cli;

/// Where the builder skill lives in the repo.
pub const SKILL_DIR: &str = "skills/nuthatch-builder";

/// Regenerate the skill's machine-generated references into `root/skills/nuthatch-builder/`. Today
/// that's `cli-reference.md`; the config reference is authored (its keys are drift-checked in CI).
pub fn write_refs(root: &Path) -> Result<()> {
    let dir = root.join(SKILL_DIR);
    std::fs::create_dir_all(&dir).with_context(|| format!("create {}", dir.display()))?;
    std::fs::write(dir.join("cli-reference.md"), generate_cli_reference())
        .context("write cli-reference.md")?;
    Ok(())
}

/// Render every (non-hidden) nuthatch subcommand and its flags to Markdown, straight from clap. Pure
/// and deterministic - same binary → byte-identical output, which is what makes the CI drift gate work.
pub fn generate_cli_reference() -> String {
    let mut out = String::new();
    out.push_str(
        "# nuthatch CLI reference\n\n\
         <!-- GENERATED by `nuthatch skill-refs` from clap metadata - do not edit by hand. -->\n\n\
         Every subcommand and flag the `nuthatch` binary exposes. Regenerate with `nuthatch skill-refs`.\n",
    );
    let cmd = Cli::command();
    let mut subs: Vec<_> = cmd.get_subcommands().collect();
    subs.sort_by_key(|c| c.get_name());
    for sub in subs {
        if sub.is_hide_set() {
            continue;
        }
        render_command(sub, "nuthatch", &mut out);
    }
    out
}

/// Render one command (and, recursively, its subcommands) under the invocation `path`.
fn render_command(cmd: &clap::Command, path: &str, out: &mut String) {
    let full = format!("{path} {}", cmd.get_name());
    out.push_str(&format!("\n## `{full}`\n\n"));
    if let Some(about) = cmd.get_about() {
        out.push_str(&collapse(&about.to_string()));
        out.push_str("\n\n");
    }

    let args: Vec<_> = cmd.get_arguments().filter(|a| !a.is_hide_set()).collect();
    if !args.is_empty() {
        for arg in args {
            let help = arg
                .get_help()
                .map(|h| collapse(&h.to_string()))
                .unwrap_or_default();
            out.push_str(&format!("- `{}` - {help}\n", arg_signature(arg)));
        }
    }

    // Nested subcommands (e.g. `roost dev`, `nest bundle`) render under their parent's path.
    let mut subs: Vec<_> = cmd.get_subcommands().collect();
    subs.sort_by_key(|c| c.get_name());
    for sub in subs {
        if sub.is_hide_set() {
            continue;
        }
        render_command(sub, &full, out);
    }
}

/// The display signature of one argument: `-s, --long <VALUE>`, `--flag`, or `<POSITIONAL>`.
fn arg_signature(arg: &clap::Arg) -> String {
    let takes_value = !matches!(
        arg.get_action(),
        clap::ArgAction::SetTrue
            | clap::ArgAction::SetFalse
            | clap::ArgAction::Help
            | clap::ArgAction::Version
    );
    let placeholder = arg.get_id().as_str().to_ascii_uppercase();
    if arg.is_positional() {
        return format!("<{placeholder}>");
    }
    let value = if takes_value {
        format!(" <{placeholder}>")
    } else {
        String::new()
    };
    match (arg.get_short(), arg.get_long()) {
        (Some(s), Some(l)) => format!("-{s}, --{l}{value}"),
        (None, Some(l)) => format!("--{l}{value}"),
        (Some(s), None) => format!("-{s}{value}"),
        (None, None) => arg.get_id().as_str().to_string(),
    }
}

/// Collapse a multi-line clap help string (from a doc comment) to a single line.
fn collapse(s: &str) -> String {
    s.split_whitespace().collect::<Vec<_>>().join(" ")
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn reference_is_deterministic_and_names_real_subcommands() {
        // Pure render → identical across calls (the property the CI drift gate relies on).
        assert_eq!(generate_cli_reference(), generate_cli_reference());
        let r = generate_cli_reference();
        // The two headline commands are present, with real flags.
        assert!(r.contains("## `nuthatch init`"));
        assert!(r.contains("## `nuthatch dev`"));
        assert!(r.contains("--chain"), "init's --chain flag is documented");
        assert!(r.contains("--seal-direct"), "dev's --seal-direct flag");
        // The hidden generator subcommand documents itself out (no section for it).
        assert!(
            !r.contains("## `nuthatch skill-refs`"),
            "the generator hides itself"
        );
    }
}
